from . import _API as _api


class Ingot(_api.BaseWavefrontSensor): ...


class ShackHartmann(_api.BaseWavefrontSensor): ...


class Pyramid(_api.BaseWavefrontSensor): ...


class BiOEdge(_api.BaseWavefrontSensor): ...
