from ._API.base_devices import BaseWavefrontSensor


class Ingot(BaseWavefrontSensor): ...


class ShackHartmann(BaseWavefrontSensor): ...


class Pyramid(BaseWavefrontSensor): ...


class BiOEdge(BaseWavefrontSensor): ...
